version: '3.0'

services: 
main:
  container_name: main
    build: 
      context: .
      env_file:
      - .development.env
      volumes:
      - .:/app
      - /app/node_modules
      ports:
      8000:8000
      command: yarn run start:dev
      depends_on:
      - postgress
      restart: always
postgress:
  container_name: postgress
  image: postgress:12
        env_file:
      - .development.env
      enviroment:
      PG_DATA: /var/lib/postgresql/data
      ports: 5432:5432
      volumes:
      - pgdata: /var/lib/postgresql/data
      restart: always
volumes:
pgdata: